### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by winston0410** [MahabirGupta/INTRO-WEB-7---Introduction-to-Javascript-Web-Development#1]
Avoid `onclick`

https://github.com/MahabirGupta/INTRO-WEB-7---Introduction-to-Javascript-Web-Development/blob/5e1a99930dc64f5cf9a82856096081c63d7d8b4f/Exercise1.html#L12

Avoid `var`, and use `const` if possible instead of `let`. If you haven't reassign value, you should use `const`

https://github.com/MahabirGupta/INTRO-WEB-7---Introduction-to-Javascript-Web-Development/blob/5e1a99930dc64f5cf9a82856096081c63d7d8b4f/Exercise1.js#L3-L6

**Comment by MahabirGupta** [comment]
Not with thanks. Zeus did not introduce const to us so had no idea about the function. Thank you for teaching.

**Comment by MahabirGupta** [comment]
Noted with thanks. Zeus did not introduce const to us so had no idea about the function. Thank you for teaching.
